name: sync bin

on:
  push:
    branches:
      - feature/mirror_bin

jobs:
  delpoy_github:
    runs-on: ubuntu-latest

    steps:
      #      - name: Checkout docs_zh
      #        uses: actions/checkout@v2
      #        with:
      #          repository: dapr/docs-zh
      #          ref: v1.0_content
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download CLI
        run: |
          cd src
          pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv run inv sync-cli

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3
#        with:
#          token: ${{ secrets.PAT_TO_DOCS_ZH }}
#          commit-message: Update content
#          committer: dapr-cn <dapr-cn@hotmail.com>
#          signoff: false
#          delete-branch: true
#          title: "Update content"
#          labels: |
#            content update
#            automated pr
#          assignees: |
#            newbe36524
#            skyao
#          reviewers: |
#            newbe36524
#            skyao
#          team-reviewers: |
#            owners
#            maintainers
